/* eslint-disable no-unused-vars */
export const Courses = [
  {
    id: 1,
    category: "shop",
    quizzes: 3,
    instructor: "Kenny White",
    star: "5",
    level: "Beginner",
    tag: "Photography",
    picture: "Image1.png",
    owner: "Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    time: 2,
    students: 45,
    levels: "All",
    lessons: 20,
    offPrice: "20.9",
    originalPrice: 0,
  },
  {
    id: 2,
    category: "shop",
    quizzes: 1,
    instructor: "John Doe",
    star: "4",
    level: "Intermidiate",
    tag: "Photography",
    picture: "Rectangle131.png",
    owner: "Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    time: 5,
    students: 156,
    levels: "All",
    lessons: 20,
    offPrice: "20.9",
    originalPrice: "70.0",
  },
  {
    id: 3,
    category: "office",
    quizzes: 4,
    instructor: "Kenny White",
    star: "2",
    level: "Intermidiate",
    tag: "Photography",
    picture: "Image3.png",
    owner: "Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    time: 3,
    students: 70,
    levels: "All",
    lessons: 20,
    offPrice: "20.9",
    originalPrice: 0,
  },
  {
    id: 4,
    category: "studio",
    quizzes: 3,
    instructor: "Kenny White",
    star: "1",
    level: "Intermidiate",
    tag: "Photography",
    picture: "Image(1).png",
    owner: "Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    time: 43,
    students: 4,
    levels: "All",
    lessons: 20,
    offPrice: "20.9",
    originalPrice: "60.0",
  },
  {
    id: 5,
    category: "university",
    quizzes: 6,
    instructor: "John Doe",
    star: "5",
    level: "Expert",
    tag: "Photography",
    picture: "Rectangle 139(1).png",
    owner: "Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    time: 1,
    students: 65,
    levels: "All",
    lessons: 20,
    offPrice: "20.9",
    originalPrice: 0,
  },
  {
    id: 6,
    category: "academy",
    quizzes: 10,
    instructor: "Kenny White",
    star: "4",
    level: "Expert",
    tag: "Photography",
    picture: "Image(2).png",
    owner: "Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    time: 8,
    students: 30,
    levels: "All",
    lessons: 20,
    offPrice: "20.9",
    originalPrice: "40.0",
  },
];